version: '3'

services:
  backend:
    build: .
    restart: always
    depends_on:
      - "db"
    ports:
      - 3000:3000
    working_dir: /usr/app/backend
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/ts-market-storage"
    command: npm run dev
    volumes:
      - ./backend/src:/usr/app/backend/src
    networks:
      - api-sequelize

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    networks:
      - api-sequelize


  frontend:
    build: .
    ports:
      - 5173:5173
    restart: always
    working_dir: /usr/app/frontend/ts-market
    command: npm run dev
    depends_on:
      - backend
    volumes:
      - ./frontend/ts-market/src:/usr/app/frontend/ts-market/src
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - api-sequelize


networks:
  api-sequelize:
    driver: bridge